name = "hugo-tailwind-nord-theme"
description = "Hugo Tailwind Nord Theme"
homepage = ""
tags = ["Hugo", "Tailwind CSS", "theme", "Nord Theme", "boilerplate"]
features = []
min_version = "0.80"

[author]
  name = "Law Zava"
  homepage = "https://github.com/lawzava/"
