theme = "hugo-tailwind-nord-theme"
languageCode = "en-us"
baseurl = "https://gohugo.io/"
title = "Hugo Tailwind Nord Theme"

author = "Law Zava"
description = "Law Zava's site"

pygmentsCodefences = true
pygmentsStyle = "rrt"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    favicon = "favicon.svg"
    disclaimer = "No Trackers. No Cookies. No Visit Logs."
    copyright = "Copyright © 2021, Law Zava, all rights reserved."
    images = ["img/lawzava.png"]
    author = "Law Zava"
    github = "https://github.com/lawzava"
    ogimage = "/img/lawzava.png"
    sitename = "Law Zava"
    description = "Law Zava's personal site"

[languages]
    [languages.en]
        languageName = "English"
        languageCode = "en-us"
        weight = 1

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        title = "home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "dome"
        name = "Dome"
        title = "Dome"
        url = "#dome"
        weight = 2
