theme = "hugo-tailwind-nord"
languageCode = "en-us"
baseurl = "https://gohugo.io/"
title = "Hugo Tailwind Nord Site"

author = "Law Zava"
description = "Law Zava's site"

# Code higlighting settings
pygmentsCodefences = true
pygmentsStyle = "rrt"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    favicon = "favicon.svg"
    disclaimer = "No Trackers. No Cookies. No Visit Logs."
    copyright = "Copyright © 2020, Law Zava, all rights reserved."
    images = ["img/lawzava.png"]
    author = "Law Zava"
    github = "https://github.com/lawzava"
    ogimage = "/img/lawzava.png"
    sitename = "Law Zava"
    description = "Law Zava's personal site"

[params.index]
    image = "/img/lawzava.svg"
    imageAlt = "Law Zava"
    title = "Law Zava"
    description = "Software Engineer & Serial Startup'eer"
    slogan = "It's boring to stay still"

[params.links]
    github = "https://github.com/lawzava"
    linkedin = "https://linkedin.com/in/lawzava"
    rss = "index.xml"

[languages]
    [languages.en]
        languageName = "English"
        languageCode = "en-us"
        weight = 1

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        title = "home"
        url = "/"
        weight = 1
